const express = require('express');
const cors = require('cors');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 3000;

// Enable CORS for development (or restriction in production)
app.use(cors());

// Serve static files from the 'dist' directory (generated by Expo export)
app.use(express.static(path.join(__dirname, 'dist')));

// Naver Search API Proxy Endpoint
app.get('/api/search', async (req, res) => {
    const query = req.query.query;
    const display = req.query.display || '5';
    const sort = req.query.sort || 'random';

    if (!query) {
        return res.status(400).json({ error: 'Missing query parameter' });
    }

    const NAVER_CLIENT_ID = process.env.EXPO_PUBLIC_NAVER_CLIENT_ID;
    const NAVER_CLIENT_SECRET = process.env.EXPO_PUBLIC_NAVER_CLIENT_SECRET;

    if (!NAVER_CLIENT_ID || !NAVER_CLIENT_SECRET) {
        console.error('Naver API keys missing on server');
        return res.status(500).json({ error: 'Server configuration error' });
    }

    try {
        const apiUrl = `https://openapi.naver.com/v1/search/local.json?query=${encodeURIComponent(query)}&display=${display}&start=1&sort=${sort}`;

        const response = await fetch(apiUrl, {
            method: 'GET',
            headers: {
                'X-Naver-Client-Id': NAVER_CLIENT_ID,
                'X-Naver-Client-Secret': NAVER_CLIENT_SECRET
            }
        });

        if (!response.ok) {
            const errorText = await response.text();
            console.error('Naver API Error:', response.status, errorText);
            return res.status(response.status).json({ error: `Naver API Error: ${response.status}`, details: errorText });
        }

        const data = await response.json();
        res.json(data);

    } catch (error) {
        console.error('Proxy Error:', error);
        res.status(500).json({ error: 'Internal Server Error', details: String(error) });
    }
});

// For any other request, send index.html (SPA support)
app.get('*', (req, res) => {
    res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

app.listen(PORT, () => {
    console.log(`Server is running on port ${PORT}`);
});
